adding security

diff --git a/dofus_retro_updater b/dofus_retro_updater
--- a/dofus_retro_updater
+++ b/dofus_retro_updater
@@ -4,20 +4,37 @@ function update {
 	sudo rm -rf "/usr/games/retro"
 	python3 dofus_retro_updater.py
 	sudo mv retro "/usr/games"
+	add_desktop_shortcut	
+
+function add_desktop_shortcut {
 	# Adding Icons and .desktop file
 	echo "[+] Adding Desktop Shortcut Icon..."
-	wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.icns"
+
+	wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.icns" -q
 	sudo mv "Dofus Retro.icns" "/usr/games/retro"
-	wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.desktop"
-	if [[ -d "/home/$USER/Desktop" ]]
+
+	if ! [[ -f "/home/$USER/Desktop/Dofus Retro.desktop" ]] || [[ -f "/home/$USER/Bureau/Dofus Retro.desktop" ]]
 	then
-		sudo mv "Dofus Retro.desktop" "/home/$USER/Desktop"
-	elif [[ -d "/home/$USER/Bureau" ]]
-	then
-		sudo mv "Dofus Retro.desktop" "/home/$USER/Bureau"
-	else
-		echo "[-] Unable to find your Desktop. You can move 'Dofus Retro.desktop' file to your Desktop if you want a Shortcut."
+		if ! [[ -f "Dofus Retro.desktop"]]
+		then
+			wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.desktop" -q
+		fi
+		
+		chmod +x "Dofus Retro.desktop"
+		
+		echo "[+] Look for the Desktop..."
+		
+		if [[ -d "/home/$USER/Desktop" ]]
+		then
+			mv "Dofus Retro.desktop" "/home/$USER/Desktop"
+		elif [[ -d "/home/$USER/Bureau" ]]
+		then
+			mv "Dofus Retro.desktop" "/home/$USER/Bureau"
+		else
+			echo "[-] Unable to find your Desktop. You can move 'Dofus Retro.desktop' file to your Desktop if you want a Shortcut."
+		fi
 	fi
+
 	echo "[+] OK."
 }
 
